# CodeRabbit configuration for Compliance Tracker

language: en-US

reviews:
  auto_review:
    enabled: true

  focus:
    - bugs
    - security
    - performance
    - best-practices
    - documentation

path_filters:
  include:
    - src/**/*.ts
    - src/**/*.tsx
    - supabase/**/*.ts
  exclude:
    - node_modules/**
    - dist/**
    - build/**
    - .env*
    - "*.test.ts"
    - "*.spec.ts"
